const pList = {
  "bottom": {
    "src": "./img/bottom.png",
    "x": 5, "y": 0, "width": 138, "height": 70,
  },
  "bullet1": {
    "src": "./img/bullet.png",
    "x": 0, "y": 0, "width": 23, "height": 26,
    "scope": "bullet",
  },
  "bullet2": {
    "src": "./img/bullet.png",
    "x": 0, "y": 50, "width": 25, "height": 29,
    "scope": "bullet",
  },
  "bullet3": {
    "src": "./img/bullet.png",
    "x": 0, "y": 100, "width": 26, "height": 31,
    "scope": "bullet",
  },
  "bullet4": {
    "src": "./img/bullet.png",
    "x": 0, "y": 150, "width": 27, "height": 33,
    "scope": "bullet",
  },
  "bullet5": {
    "src": "./img/bullet.png",
    "x": 0, "y": 200, "width": 29, "height": 34,
    "scope": "bullet",
  },
  "bullet6": {
    "src": "./img/bullet.png",
    "x": 0, "y": 250, "width": 30, "height": 35,
    "scope": "bullet",
  },
  "bullet7": {
    "src": "./img/bullet.png",
    "x": 0, "y": 300, "width": 28, "height": 44,
    "scope": "bullet",
  },
  "cannon1": {
    "src": "./img/cannon1.png",
    "x": 0, "y": 0, "width": 74, "height": 74,
    "scope": "cannon",
  },
  "cannon2": {
    "src": "./img/cannon2.png",
    "x": 0, "y": 0, "width": 74, "height": 76,
    "scope": "cannon",
  },
  "cannon3": {
    "src": "./img/cannon3.png",
    "x": 0, "y": 0, "width": 74, "height": 76,
    "scope": "cannon",
  },
  "cannon4": {
    "src": "./img/cannon4.png",
    "x": 0, "y": 0, "width": 74, "height": 83,
    "scope": "cannon",
  },
  "cannon5": {
    "src": "./img/cannon5.png",
    "x": 0, "y": 0, "width": 74, "height": 85,
    "scope": "cannon",
  },
  "cannon6": {
    "src": "./img/cannon6.png",
    "x": 0, "y": 0, "width": 74, "height": 90,
    "scope": "cannon",
  },
  "cannon7": {
    "src": "./img/cannon7.png",
    "x": 0, "y": 0, "width": 74, "height": 94,
    "scope": "cannon",
  },
  "fish1": {
    "src": "./img/fish1.png",
    "x": 0, "y": 0, "width": 55, "height": 37,
    "scope": "fish",
    "frameAlive": [0, 3],
    "frameDie": [4, 7],
    "totalFrame": 8,
  },
  "fish2": {
    "src": "./img/fish2.png",
    "x": 0, "y": 0, "width": 78, "height": 64,
    "scope": "fish",
    "frameAlive": [0, 3],
    "frameDie": [4, 7],
    "totalFrame": 8,
  },
  "fish3": {
    "src": "./img/fish3.png",
    "x": 0, "y": 0, "width": 72, "height": 56,
    "scope": "fish",
    "frameAlive": [0, 3],
    "frameDie": [4, 7],
    "totalFrame": 8,
  },
  "fish4": {
    "src": "./img/fish4.png",
    "x": 0, "y": 0, "width": 77, "height": 59,
    "scope": "fish",
    "frameAlive": [0, 3],
    "frameDie": [4, 7],
    "totalFrame": 8,
  },
  "fish5": {
    "src": "./img/fish5.png",
    "x": 0, "y": 0, "width": 107, "height": 122,
    "scope": "fish",
    "frameAlive": [0, 3],
    "frameDie": [4, 7],
    "totalFrame": 8,
  },
  "fish6": {
    "src": "./img/fish6.png",
    "x": 0, "y": 0, "width": 105, "height": 79,
    "scope": "fish",
    "frameAlive": [0, 5],
    "frameDie": [6, 11],
    "totalFrame": 12,
  },
  "fish7": {
    "src": "./img/fish7.png",
    "x": 0, "y": 0, "width": 92, "height": 151,
    "scope": "fish",
    "frameAlive": [0, 4],
    "frameDie": [5, 9],
    "totalFrame": 10,
  },
  "fish8": {
    "src": "./img/fish8.png",
    "x": 0, "y": 0, "width": 174, "height": 126,
    "scope": "fish",
    "frameAlive": [0, 5],
    "frameDie": [6, 11],
    "totalFrame": 12,
  },
  "fish9": {
    "src": "./img/fish9.png",
    "x": 0, "y": 0, "width": 166, "height": 183,
    "scope": "fish",
    "frameAlive": [0, 5],
    "frameDie": [6, 11],
    "totalFrame": 12,
  },
  "fish10": {
    "src": "./img/fish10.png",
    "x": 0, "y": 0, "width": 178, "height": 187,
    "scope": "fish",
    "frameAlive": [0, 4],
    "frameDie": [5, 9],
    "totalFrame": 10,
  },
  "fish11": {
    "src": "./img/fish11.png",
    "x": 0, "y": 0, "width": 509, "height": 270,
    "scope": "fish",
    "frameAlive": [0, 5],
    "frameDie": [6, 11],
    "totalFrame": 12,
  },
  "fish12": {
    "src": "./img/fish12.png",
    "x": 0, "y": 0, "width": 516, "height": 273,
    "scope": "fish",
    "frameAlive": [0, 5],
    "frameDie": [6, 11],
    "totalFrame": 12,
  },
  "net1": {
    "src": "./img/net.png",
    "x": 0, "y": 0, "width": 90, "height": 90,
    "scope": "net",
  },
  "net2": {
    "src": "./img/net.png",
    "x": 0, "y": 200, "width": 110, "height": 110,
    "scope": "net",
  },
  "net3": {
    "src": "./img/net.png",
    "x": 0, "y": 400, "width": 128, "height": 128,
    "scope": "net",
  },
  "net4": {
    "src": "./img/net.png",
    "x": 0, "y": 600, "width": 150, "height": 150,
    "scope": "net",
  },
  "net5": {
    "src": "./img/net.png",
    "x": 0, "y": 800, "width": 163, "height": 163,
    "scope": "net",
  },
  "net6": {
    "src": "./img/net.png",
    "x": 0, "y": 1000, "width": 182, "height": 182,
    "scope": "net",
  },
  "net7": {
    "src": "./img/net.png",
    "x": 0, "y": 1200, "width": 200, "height": 200,
    "scope": "net",
  },
  "coin1": {
    "src": "./img/coinAni1.png",
    "x": 0, "y": 0, "width": 60, "height": 60,
    "scope": "coin",
  },
  "coin2": {
    "src": "./img/coinAni2.png",
    "x": 0, "y": 0, "width": 60, "height": 60,
    "scope": "coin",
  },
  "coinText": {
    "src": "./img/coinText.png",
    "x": 0, "y": 0, "width": 36, "height": 49,
    "scope": "coinText",
  },
  "numberBlack": {
    "src": "./img/number_black.png",
    "x": 0, "y": 0, "width": 20, "height": 24,
  }
}